# Generated by Django 2.1.5 on 2019-02-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreakDownBus',
            fields=[
                ('bus_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('route_no', models.IntegerField()),
                ('breakDown_Lat', models.CharField(max_length=100)),
                ('breakDown_Lon', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('supply_bus_assign', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('bus_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('route_no', models.IntegerField()),
            ],
        ),
    ]
