# Generated by Django 2.1.5 on 2019-02-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusDepot',
            fields=[
                ('depotName', models.CharField(max_length=100)),
                ('depotNo', models.IntegerField(primary_key=True, serialize=False)),
                ('depotLat', models.CharField(max_length=100)),
                ('depotLon', models.CharField(max_length=100)),
                ('supplyBusValue', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='supply',
            name='depotno',
            field=models.IntegerField(default=0),
        ),
    ]
