# Generated by Django 2.1.5 on 2019-02-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190212_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusNo', models.CharField(max_length=100)),
                ('routeNo', models.IntegerField()),
                ('logTime', models.CharField(max_length=255)),
                ('location', models.TextField(blank=True, null=True)),
                ('depotAssigned', models.CharField(max_length=255)),
                ('currentStatus', models.CharField(max_length=255)),
            ],
        ),
    ]
