# Generated by Django 2.1.5 on 2019-02-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_supply_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdepot',
            name='supplyBusValue',
            field=models.IntegerField(null=True),
        ),
    ]
