# Generated by Django 2.1.5 on 2019-02-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190212_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdownbus',
            name='supply_bus_assign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supply',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
