# Generated by Django 2.1.5 on 2019-02-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190212_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='supply_bus_no',
            field=models.IntegerField(default=0),
        ),
    ]
